# ALERTAS

LOW_BATTERY1 = 1
LOW_BATTERY2 = 2
STUCK_RUDDER1 = 3
STUCK_RUDDER2 = 4
STUCK_SAIL1 = 5
STUCK_SAIL2 = 6
GPS_OFF = 7
GIROS_OFF = 8
AGAIST_WIND = 9
HIGH_WINDVEL = 10
DESVIO_RUMBO = 11
HIGH_INCLINACION = 12
WATER_FILTERING = 13
FARAWAY_CENTER = 14
LOST_BOARD = 15 # PERDIDAD DE COMUNICACION PLACA RPI

 